In [161]:
import torch

# Torch Tensors

In [162]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [163]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [164]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [165]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [166]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [167]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [168]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [169]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [170]:
print(c.mean())

tensor(2.5833)


In [171]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [172]:
print(c.std())

tensor(1.5050)


In [173]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [174]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12)) # b.view(torch.numel(b))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[ 0.2029,  0.8934, -0.4005, -0.9532],
         [-2.2885, -1.0853,  1.0875, -0.5957],
         [ 0.7520,  0.0903,  0.2111,  1.4467]],

        [[-0.3731, -0.5779,  0.1414, -0.5159],
         [ 1.4012,  0.1266, -0.3228,  0.0574],
         [ 0.5165, -0.1876,  0.0487, -0.1883]]])
tensor([[ 0.2029,  0.8934, -0.4005, -0.9532, -2.2885, -1.0853,  1.0875, -0.5957,
          0.7520,  0.0903,  0.2111,  1.4467],
        [-0.3731, -0.5779,  0.1414, -0.5159,  1.4012,  0.1266, -0.3228,  0.0574,
          0.5165, -0.1876,  0.0487, -0.1883]])
tensor([[ 0.2029,  0.8934, -0.4005, -0.9532, -2.2885

In [175]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.3604, 0.9168, 0.9657, 0.4956],
        [0.6885, 0.4653, 0.6004, 0.1490],
        [0.3053, 0.1532, 0.4192, 0.8803],
        [0.5777, 0.2332, 0.3535, 0.9595]])


In [176]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.4777,  0.1695,  0.1357, -0.6807],
        [ 0.0394, -0.8534,  0.4746, -1.0393],
        [ 1.1210, -0.9978,  1.0277, -0.6407],
        [ 0.6306, -1.2839, -0.6266,  0.2609]])
torch.float32


In [177]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([6, 8, 9, 6, 9])
torch.int64


In [178]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 7, 7],
        [9, 9, 8],
        [6, 9, 9]])


In [179]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [180]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [181]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[ 0.1202,  1.0468,  0.1709,  1.4423],
        [-2.0891, -0.1915, -0.3010, -0.3598],
        [-0.8223,  1.2320,  0.0863, -1.2183],
        [-0.5777, -0.4279,  0.3628, -0.1150]], dtype=torch.float64)


In [182]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[-0.1173,  1.0863,  1.1014, -0.1851],
        [ 0.7278, -0.3881,  1.0750, -0.8903],
        [ 1.4262, -0.8446,  1.4469,  0.2396],
        [ 1.2083, -1.0508, -0.2731,  1.2204]])


In [183]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[-0.1173,  1.0863,  1.1014, -0.1851],
        [ 0.7278, -0.3881,  1.0750, -0.8903],
        [ 1.4262, -0.8446,  1.4469,  0.2396],
        [ 1.2083, -1.0508, -0.2731,  1.2204]])


In [184]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 1.0863, -0.3881, -0.8446, -1.0508])
tensor([[-0.1173,  1.0863],
        [ 0.7278, -0.3881],
        [ 1.4262, -0.8446],
        [ 1.2083, -1.0508]])
tensor([[-0.1173,  1.0863,  1.1014, -0.1851],
        [ 0.7278, -0.3881,  1.0750, -0.8903],
        [ 1.4262, -0.8446,  1.4469,  0.2396]])
tensor(0.2396)
0.23956990242004395
tensor([ 1.4262, -0.8446,  1.4469,  0.2396])


## Numpy Bridge

In [185]:
import numpy as np

In [186]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [187]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [188]:
#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[-0.1173,  1.0863,  1.1014, -0.1851],
        [ 0.7278, -0.3881,  1.0750, -0.8903],
        [ 1.4262, -0.8446,  1.4469,  0.2396],
        [ 1.2083, -1.0508, -0.2731,  1.2204]], device='cuda:0')


In [189]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[-0.1173,  1.0863,  1.1014, -0.1851],
        [ 0.7278, -0.3881,  1.0750, -0.8903],
        [ 1.4262, -0.8446,  1.4469,  0.2396],
        [ 1.2083, -1.0508, -0.2731,  1.2204]], device='cuda:0')


In [190]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [191]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [192]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 0.8844, -1.1220, -0.3608, -0.2728,  2.1877],
        [-0.1310, -0.7426, -0.6638,  0.0268,  0.7891]])
tensor([[-1.8516,  1.7847, -1.4076, -0.0714, -1.2053],
        [-1.4407, -0.1134, -0.3316, -0.1883,  0.5234],
        [-1.4477, -0.7607, -0.9126,  1.9791,  0.2906]])


tensor([[ 0.8844, -1.1220, -0.3608, -0.2728,  2.1877],
        [-0.1310, -0.7426, -0.6638,  0.0268,  0.7891],
        [-1.8516,  1.7847, -1.4076, -0.0714, -1.2053],
        [-1.4407, -0.1134, -0.3316, -0.1883,  0.5234],
        [-1.4477, -0.7607, -0.9126,  1.9791,  0.2906]])


tensor([[ 0.0551, -0.4058,  0.5091],
        [-0.2056, -0.0963,  1.1578]])
tensor([[ 0.8986, -0.3741,  0.4614,  0.5760,  2.0308],
        [ 0.2882,  1.0375,  1.9188, -1.3010, -1.0068]])


tensor([[ 0.0551, -0.4058,  0.5091,  0.8986, -0.3741,  0.4614,  0.5760,  2.0308],
        [-0.2056, -0.0963,  1.1578,  0.2882,  1.0375,  1.9188, -1.3010, -1.0068]])




## Adding Dimensions to Tensors

In [193]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.0833, 0.4278, 0.6400, 0.1747],
         [0.2213, 0.0517, 0.0661, 0.8705],
         [0.6298, 0.7834, 0.5219, 0.8293]],

        [[0.9208, 0.2288, 0.8793, 0.2428],
         [0.7200, 0.8787, 0.6368, 0.1205],
         [0.0711, 0.2803, 0.7774, 0.6435]]])


tensor([[0.6400, 0.0661, 0.5219],
        [0.8793, 0.6368, 0.7774]])
torch.Size([2, 3])


tensor([[[0.6400],
         [0.0661],
         [0.5219]],

        [[0.8793],
         [0.6368],
         [0.7774]]])
torch.Size([2, 3, 1])


## AutoGrad

In [194]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [195]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [196]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [197]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [198]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
