## Word Embeddings

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [5]:
#The indices of the words represent the values in the lookup table
word_to_idx = {"I": 0, "love": 1, "eating":2, "and":3, "sleeping":4}
embeddings = nn.Embedding(5, 7)    # 5 words in vocab, embedding size is 7
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)

tensor([1])


In [6]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[-0.2359,  0.6844,  0.6780,  0.2297, -2.3219, -1.2708,  2.8252]],
       grad_fn=<EmbeddingBackward>)
torch.Size([1, 7])


In [7]:
all_ind = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[ 0.4366, -1.7802, -0.8577, -1.9313,  0.1442, -1.4793,  0.4688],
        [-0.2359,  0.6844,  0.6780,  0.2297, -2.3219, -1.2708,  2.8252],
        [-1.0484, -0.0323,  1.3816,  0.6635, -0.0879, -0.6409, -0.8855],
        [ 1.9287, -0.8252,  1.3496,  0.6733, -0.1352,  0.1526,  0.7974],
        [-0.2229, -2.2388, -1.5800,  0.1623,  0.3447,  0.4005,  1.5951]],
       grad_fn=<EmbeddingBackward>)
torch.Size([5, 7])


## Exercise: N-Gram Skip Model
### Given a sequence of words, we want to predict the ith word of the sequence: P(w(i)|w(i-1), w(i-2), .....)
#### Source: https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html#an-example-n-gram-language-modeling  
